<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>app-payment_My Payment Options Add new card_812b05</name>
   <tag></tag>
   <elementGuidId>0c013439-6391-4d88-a08f-e55b9c5301bd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>app-payment.ng-star-inserted</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='EN'])[1]/following::app-payment[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>app-payment</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>app-payment</value>
      <webElementGuid>94f7e29f-a845-4191-8d74-6d75f25b5662</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-star-inserted</value>
      <webElementGuid>352b60b6-70e7-48e4-9782-4b5340261bdf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>My Payment Options Add new card  Add a credit or debit card Name *Card Number * Please enter a valid sixteen digit card number. 123456789101112Expiry Month *20802081208220832084208520862087208820892090209120922093209420952096209720982099Expiry Year * Please enter an expiry year.  send  Submit Pay using walletWallet Balance 0.00 Pay 10.45¤  Add a coupon  Add a coupon code to receive discounts Coupon *Need a coupon code? Follow us on Twitter or Facebook for monthly coupons and other spam!0/10 redeem  Redeem  Other payment options Donations (Thank you for supporting OWASP Juice Shop!)  Credit CardMerchandise (Official stores for OWASP Juice Shop apparel, mugs and stickers!)  Spreadshirt (US) Spreadshirt (DE) StickerYou Leanpub OpenSea navigate_before  Back  navigate_next ContinueYou can review this order before it is finalized.</value>
      <webElementGuid>4a47eaa1-d9fe-44ce-871f-2e8b7f29110f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;fontawesome-i2svg-active fontawesome-i2svg-complete&quot;]/body[@class=&quot;mat-app-background bluegrey-lightgreen-theme&quot;]/app-root[1]/div[@class=&quot;mat-typography&quot;]/mat-sidenav-container[@class=&quot;mat-drawer-container mat-sidenav-container&quot;]/mat-sidenav-content[@class=&quot;mat-drawer-content mat-sidenav-content ng-star-inserted&quot;]/app-payment[@class=&quot;ng-star-inserted&quot;]</value>
      <webElementGuid>c81955d1-c236-46b1-b206-7eb271d8b9d6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='EN'])[1]/following::app-payment[1]</value>
      <webElementGuid>71ec2496-0cc9-42be-9164-460def933b9a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Your Basket'])[1]/following::app-payment[1]</value>
      <webElementGuid>d9d438e3-92fb-40bb-b60c-48e4d6a51aba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//app-payment</value>
      <webElementGuid>750b95fa-dc7b-403a-a3bd-70f778e8d328</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//app-payment[(text() = 'My Payment Options Add new card  Add a credit or debit card Name *Card Number * Please enter a valid sixteen digit card number. 123456789101112Expiry Month *20802081208220832084208520862087208820892090209120922093209420952096209720982099Expiry Year * Please enter an expiry year.  send  Submit Pay using walletWallet Balance 0.00 Pay 10.45¤  Add a coupon  Add a coupon code to receive discounts Coupon *Need a coupon code? Follow us on Twitter or Facebook for monthly coupons and other spam!0/10 redeem  Redeem  Other payment options Donations (Thank you for supporting OWASP Juice Shop!)  Credit CardMerchandise (Official stores for OWASP Juice Shop apparel, mugs and stickers!)  Spreadshirt (US) Spreadshirt (DE) StickerYou Leanpub OpenSea navigate_before  Back  navigate_next ContinueYou can review this order before it is finalized.' or . = 'My Payment Options Add new card  Add a credit or debit card Name *Card Number * Please enter a valid sixteen digit card number. 123456789101112Expiry Month *20802081208220832084208520862087208820892090209120922093209420952096209720982099Expiry Year * Please enter an expiry year.  send  Submit Pay using walletWallet Balance 0.00 Pay 10.45¤  Add a coupon  Add a coupon code to receive discounts Coupon *Need a coupon code? Follow us on Twitter or Facebook for monthly coupons and other spam!0/10 redeem  Redeem  Other payment options Donations (Thank you for supporting OWASP Juice Shop!)  Credit CardMerchandise (Official stores for OWASP Juice Shop apparel, mugs and stickers!)  Spreadshirt (US) Spreadshirt (DE) StickerYou Leanpub OpenSea navigate_before  Back  navigate_next ContinueYou can review this order before it is finalized.')]</value>
      <webElementGuid>bca596a8-bd1e-4c17-a8b2-15e03a04bc72</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
