<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_This cannot be changed later_security_f37fc9</name>
   <tag></tag>
   <elementGuidId>60d0bab0-7953-4fde-895f-1ab0cc05b52b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#securityAnswerControl</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='securityAnswerControl']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Answer to your security question&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f25c0052-f4a1-4690-b87f-3d844cf9fffd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>securityAnswerControl</value>
      <webElementGuid>02a86e9d-5459-4e3c-973c-897bed52eebb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>424b4863-3158-4228-a3af-7d3e594a93bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Field for the answer to the security question</value>
      <webElementGuid>aa9706c8-313a-482b-a21b-dfdcbf719f1f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-input-element mat-form-field-autofill-control ng-tns-c21-18 ng-untouched ng-pristine ng-invalid cdk-text-field-autofill-monitored</value>
      <webElementGuid>7173eea9-282e-400e-9c60-134abc15b9f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Answer to your security question</value>
      <webElementGuid>c40a3185-df60-4bdd-b74e-fd7b39e9748d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-placeholder</name>
      <type>Main</type>
      <value>Answer to your security question</value>
      <webElementGuid>0f0f8f4a-e273-4dd0-8b5b-30cb83bf9f31</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>9a637fd5-e3f7-4af5-a303-d76053134db7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;securityAnswerControl&quot;)</value>
      <webElementGuid>53862232-8a04-44e4-aa0d-b3aee87a2cf8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='securityAnswerControl']</value>
      <webElementGuid>0591aad9-c56c-4beb-9426-5a51c704b6fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='registration-form']/div/mat-form-field[2]/div/div/div[3]/input</value>
      <webElementGuid>8bf5f036-bf62-48d8-bf41-126c544b921f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/mat-form-field[2]/div/div/div[3]/input</value>
      <webElementGuid>561735d6-e077-44d8-9a16-323f1ba5985e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'securityAnswerControl' and @type = 'text' and @placeholder = 'Answer to your security question']</value>
      <webElementGuid>712f82dd-55fb-4c13-a41e-6c1167e2e627</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
